package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"

	"github.com/jukemori/timeline-generator/graph/generated"
	"github.com/jukemori/timeline-generator/graph/model"
)

// GenerateTimeline is the resolver for the generateTimeline field.
func (r *mutationResolver) GenerateTimeline(ctx context.Context, input model.TimelineInput) (*model.Timeline, error) {
	return r.OpenAIClient.GenerateTimeline(ctx, input)
}

// Timeline is the resolver for the timeline field.
func (r *queryResolver) Timeline(ctx context.Context, id string) (*model.Timeline, error) {
	// In a real app, you would fetch the timeline from a database
	return nil, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
